[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["hamer", "DWPose"]

[project]
name = "hamer"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "torch==2.8.0",
    "numpy==1.26.4",
    "onnxruntime-gpu"
]
